#Expression Testing
name: expressions-testing
on: [push, workflow_dispatch]
jobs:
  first-expression:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "${{toJSON(github)}}"
