#Expression Testing
name: expressions-testing
on: [push, workflow_dispatch]
jobs:
  first-expression:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "${{toJSON(github)}}"

  second-expression:
    runs-on: ubuntu-latest
    needs: [first-expression]        
    steps:
      - name: needs testing
        run: echo "needs is successful"
