name: first-gt-actions
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: |
          echo "First output"
          echo "Second output"
      - name: bye
        run: echo "Bye"
